/**
 * 발음이 **없는** 자리. (spec.md §5)
 *
 * 듣기 카드는 소리가 단서다. 파일이 없으면 문제가 성립하지 않으므로 그 카드는
 * 아예 만들지 않고 재인 카드를 낸다 — 소리 없는 듣기 문제를 내는 것보다
 * 조용히 다른 문제를 내는 편이 낫다.
 *
 * 정적 내보내기(`output: 'export'`)라 앱이 도는 중에 파일 존재를 물어볼 서버가
 * 없다. 그래서 **없는 것만** 목록으로 적어 둔다. 지금은 20,671자리가 모두 차
 * 있어 비어 있고, 비었다는 사실 자체가 이 파일의 값이다 — 있는 것을 다 적으면
 * 400KB짜리 목록이 번들에 실린다.
 *
 *   node scripts/audio.ts manifest    다시 만든다
 *
 * 낡으면 `pnpm check`가 경고한다. 콘텐츠를 넣고 발음을 아직 안 만들었는데 이
 * 목록이 옛날 그대로면 듣기 카드가 빈 소리를 내기 때문이다.
 */
export const AUDIO_MISSING: ReadonlySet<string> = new Set([
  'de/beach-ball',
  'de/beach-umbrella',
  'de/changing-table',
  'de/cuboid',
  'de/diagonal',
  'de/fanny-pack',
  'de/greengrocer',
  'de/handshake',
  'de/juggler',
  'de/lumberjack',
  'de/magician',
  'de/octagon',
  'de/parallelogram',
  'de/pendulum-clock',
  'de/pentagon',
  'de/picnic-blanket',
  'de/pie-chart',
  'de/pregnant-woman',
  'de/quarter-past',
  'de/right-angle',
  'de/rocking-horse',
  'de/sculptor',
  'de/sector',
  'de/semicircle',
  'de/snow-globe',
  'de/surveyor',
  'de/tricycle',
  'de/wedding-dress',
  'de/wetsuit',
  'en/beach-ball',
  'en/beach-umbrella',
  'en/changing-table',
  'en/cuboid',
  'en/diagonal',
  'en/fanny-pack',
  'en/greengrocer',
  'en/handshake',
  'en/juggler',
  'en/lumberjack',
  'en/magician',
  'en/octagon',
  'en/parallelogram',
  'en/pendulum-clock',
  'en/pentagon',
  'en/picnic-blanket',
  'en/pie-chart',
  'en/pregnant-woman',
  'en/quarter-past',
  'en/right-angle',
  'en/rocking-horse',
  'en/sculptor',
  'en/sector',
  'en/semicircle',
  'en/snow-globe',
  'en/surveyor',
  'en/tricycle',
  'en/wedding-dress',
  'en/wetsuit',
  'es/beach-ball',
  'es/beach-umbrella',
  'es/changing-table',
  'es/cuboid',
  'es/diagonal',
  'es/fanny-pack',
  'es/greengrocer',
  'es/handshake',
  'es/juggler',
  'es/lumberjack',
  'es/magician',
  'es/octagon',
  'es/parallelogram',
  'es/pendulum-clock',
  'es/pentagon',
  'es/picnic-blanket',
  'es/pie-chart',
  'es/pregnant-woman',
  'es/quarter-past',
  'es/right-angle',
  'es/rocking-horse',
  'es/sculptor',
  'es/sector',
  'es/semicircle',
  'es/snow-globe',
  'es/surveyor',
  'es/tricycle',
  'es/wedding-dress',
  'es/wetsuit',
  'fr/beach-ball',
  'fr/beach-umbrella',
  'fr/changing-table',
  'fr/cuboid',
  'fr/diagonal',
  'fr/fanny-pack',
  'fr/greengrocer',
  'fr/handshake',
  'fr/juggler',
  'fr/lumberjack',
  'fr/magician',
  'fr/octagon',
  'fr/parallelogram',
  'fr/pendulum-clock',
  'fr/pentagon',
  'fr/picnic-blanket',
  'fr/pie-chart',
  'fr/pregnant-woman',
  'fr/quarter-past',
  'fr/right-angle',
  'fr/rocking-horse',
  'fr/sculptor',
  'fr/sector',
  'fr/semicircle',
  'fr/snow-globe',
  'fr/surveyor',
  'fr/tricycle',
  'fr/wedding-dress',
  'fr/wetsuit',
  'ja/beach-ball',
  'ja/beach-umbrella',
  'ja/changing-table',
  'ja/cuboid',
  'ja/diagonal',
  'ja/fanny-pack',
  'ja/greengrocer',
  'ja/handshake',
  'ja/juggler',
  'ja/lumberjack',
  'ja/magician',
  'ja/octagon',
  'ja/parallelogram',
  'ja/pendulum-clock',
  'ja/pentagon',
  'ja/picnic-blanket',
  'ja/pie-chart',
  'ja/pregnant-woman',
  'ja/quarter-past',
  'ja/right-angle',
  'ja/rocking-horse',
  'ja/sculptor',
  'ja/sector',
  'ja/semicircle',
  'ja/snow-globe',
  'ja/surveyor',
  'ja/tricycle',
  'ja/wedding-dress',
  'ja/wetsuit',
  'ru/beach-ball',
  'ru/beach-umbrella',
  'ru/changing-table',
  'ru/cuboid',
  'ru/diagonal',
  'ru/fanny-pack',
  'ru/greengrocer',
  'ru/handshake',
  'ru/juggler',
  'ru/lumberjack',
  'ru/magician',
  'ru/octagon',
  'ru/parallelogram',
  'ru/pendulum-clock',
  'ru/pentagon',
  'ru/picnic-blanket',
  'ru/pie-chart',
  'ru/pregnant-woman',
  'ru/quarter-past',
  'ru/right-angle',
  'ru/rocking-horse',
  'ru/sculptor',
  'ru/sector',
  'ru/semicircle',
  'ru/snow-globe',
  'ru/surveyor',
  'ru/tricycle',
  'ru/wedding-dress',
  'ru/wetsuit',
  'zh/beach-ball',
  'zh/beach-umbrella',
  'zh/changing-table',
  'zh/cuboid',
  'zh/diagonal',
  'zh/fanny-pack',
  'zh/greengrocer',
  'zh/handshake',
  'zh/juggler',
  'zh/lumberjack',
  'zh/magician',
  'zh/octagon',
  'zh/parallelogram',
  'zh/pendulum-clock',
  'zh/pentagon',
  'zh/picnic-blanket',
  'zh/pie-chart',
  'zh/pregnant-woman',
  'zh/quarter-past',
  'zh/right-angle',
  'zh/rocking-horse',
  'zh/sculptor',
  'zh/sector',
  'zh/semicircle',
  'zh/snow-globe',
  'zh/surveyor',
  'zh/tricycle',
  'zh/wedding-dress',
  'zh/wetsuit',
])

/** 그 언어에 그 개념의 발음이 있는가 */
export function hasAudio(slug: string, lang: string): boolean {
  return !AUDIO_MISSING.has(`${lang}/${slug}`)
}

/**
 * 예문 소리가 **있는** 자리. 낱말과 반대로 적는다.
 *
 * 낱말은 20,671자리가 거의 다 차 있어 **없는 것**을 적는 편이 짧다. 예문은
 * 42,000자리가 거의 다 비어 있어 **있는 것**을 적는 편이 짧다. 같은 이유로
 * 방향만 뒤집었다 — 목록이 번들에 실리므로 짧은 쪽을 고른다.
 *
 * 열쇠는 `{lang}/{slug}-{index}-{해시}`다. 해시가 문장에서 나오므로(lib/entries.ts)
 * 예문을 고치면 열쇠가 달라지고, 이 목록에 없으니 버튼이 조용히 안 뜬다.
 *
 *   node scripts/audio.ts manifest    다시 만든다
 */
export const EXAMPLE_AUDIO: ReadonlySet<string> = new Set([])
